sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java
sonar.java.binaries=backend/target/classes

sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
sonar.junit.reportPaths=backend/target/surefire-reports

sonar.exclusions=backend/target/**,frontend/node_modules/**,frontend/dist/**
